import Head from "next/head";
import Image from "next/image";
import { GetStaticProps } from "next";
import { getExperiments, getEntry } from "@/lib/api";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { MyComponent } from "@/components/MyComponent";
import { Experience } from "@ninetailed/experience.js-next";
import { ExperienceMapper } from "@ninetailed/experience.js-utils-contentful";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ entry }) {
  const mappedExperiences = entry.fields.nt_experiences
    .filter(ExperienceMapper.isExperienceEntry)
    .map(ExperienceMapper.mapExperience);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Experience
          {...entry}
          id={entry.sys.id}
          component={MyComponent}
          experiences={mappedExperiences}
        />
        <Link href="/about">Go to the about page</Link>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ preview }) => {
  const [entry, experiments] = await Promise.all([
    getEntry({
      preview,
      title: "Welcome to your multi-chain future",
      entryContentType: "heroSection",
    }),
    getExperiments(),
  ]);
  return {
    props: { entry, ninetailed: { experiments } },
    revalidate: 1, // Demo purposes only!
  };
};
